processor-toolbox:

    processors:

        - type: egg-processor
          name: egg1
        - type: forward-fftw
          name: fft1
        - type: convert-to-power
          name: to-ps1

        - type: egg-processor
          name: egg2
        - type: forward-fftw
          name: fft2
        - type: convert-to-power
          name: to-ps2

        - type: data-accumulator
          name: acc
        - type: gain-variation
          name: gainvar

        - type: variable-spectrum-discriminator
          name: discrim
        - type: sequential-track-finder
          name: seq-tr-clust
        - type: overlapping-track-clustering
          name: otc
        - type: iterative-track-clustering
          name: itc
        - type: track-proc-ws
          name: tr-proc-ws
        - type: multi-peak-track-builder
          name: mptb
        - type: multi-peak-event-builder
          name: mpeb

        - type: apply-cut
          name: ac1b
        - type: apply-cut
          name: event-nup-cut
        - type: apply-cut
          name: event-time-cut

        - type: basic-root-writer
          name: brw
        - type: root-tree-writer
          name: trw

        # Third pass
        - type: egg-processor
          name: egg3
        - type: forward-fftw
          name: fft3
        - type: convert-to-power
          name: to-ps3
        - type: spectrogram-collector
          name: spectrogram1
        - type: basic-root-writer
          name: writer






    connections:

        # Header processing
        - signal: "egg1:header"
          slot: "fft1:header"

        - signal: "egg1:ts"
          slot: "fft1:ts-fftw"

        # First egg processing
        - signal: "fft1:fft"
          slot: "to-ps1:fs-fftw-to-psd"

        - signal: "to-ps1:psd"
          slot: "acc:ps"

        - signal: "acc:ps-finished"
          slot: "gainvar:ps-var"

        - signal: "acc:ps-finished"
          slot: "brw:psd"                 # Write accumulated PSD histogram

        - signal: "gainvar:gain-var"
          slot: "brw:gain-var"            # Write gain-var histogram

        - signal: "gainvar:gain-var"
          slot: "discrim:gv"

        # Second egg processing
        - signal: "egg2:header"
          slot: "fft2:header"

        - signal: "egg2:ts"
          slot: "fft2:ts-fftw"

        - signal: "fft2:fft"
          slot: "to-ps2:fs-fftw-to-psd"

        - signal: "to-ps2:psd"
          slot: "discrim:ps-pre"

        - signal: "discrim:disc-1d"
          slot: "seq-tr-clust:disc-1d"

        #- signal: "discrim:disc-1d"
        #  slot: "trw:disc-1d"             # Writing discriminated points to ROOT tree

        - signal: "seq-tr-clust:seq-cand"
          slot: "otc:seq-cand"

        - signal: "otc:seq-cand"
          slot: "itc:seq-cand"

        - signal: "itc:seq-cand"
          slot: "ac1b:apply"

        - signal: "ac1b:pass"
          slot: "tr-proc-ws:seq-cand"

        - signal: "tr-proc-ws:track"
          slot: "mptb:track"

        - signal: "tr-proc-ws:track"
          slot: "trw:proc-track"          # Write processed tracks to a ROOT tree

        - signal: "egg2:egg-done"
          slot: "seq-tr-clust:done"

        - signal: "seq-tr-clust:clustering-done"
          slot: "otc:do-clustering"

        - signal: "otc:clustering-done"
          slot: "itc:do-clustering"

        - signal: "itc:clustering-done"
          slot: "mptb:do-clustering"

        - signal: "mptb:mpt"
          slot: "mpeb:mpt"

        - signal: "mptb:mpt-done"
          slot: "mpeb:do-clustering"

        - signal: "mpeb:event"
          slot: "event-nup-cut:apply"

        - signal: "event-nup-cut:pass"
          slot: "event-time-cut:apply"

        - signal: "event-time-cut:pass"
          slot: "trw:mt-event"

        # Third pass: grabbing points around found tracks from previous pass

        - signal: "event-time-cut:pass"
          slot: "spectrogram1:mp-event"

        - signal: "egg3:header"
          slot: "fft3:header"

        - signal: "egg3:ts"
          slot: "fft3:ts-fftw"

        - signal: "fft3:fft"
          slot: "to-ps3:fs-fftw-to-psd"

        - signal: "to-ps3:psd"
          slot: "spectrogram1:ps"

        - signal: "spectrogram1:ps-coll"
          slot: "writer:multi-ps"

        #- signal: "egg3:egg-done"
        #  slot: "writer:write-file"



    run-queue:
        - egg1
        - egg2
        - egg3


egg1:
    filename: "foo.egg"
    egg-reader: egg3
    number-of-slices: 244
    start-record: 0
    slice-size: 4096
    progress-report-interval: 10000

fft1:
    transform-flag: ESTIMATE

acc:
    number-to-average: 0
    signal-interval: 0

gainvar:
    normalize: false
    min-frequency: 0
    max-frequency: 100e6
    fit-points: 5

egg2:
    filename: "foo.egg"
    egg-reader: egg3
    number-of-slices: 0
    start-record: 0
    slice-size: 4096
    progress-report-interval: 10000

fft2:
    transform-flag: ESTIMATE

discrim:
    min-frequency: 5e6         # Here we chop the frequency range to (100 +/-
    max-frequency: 95e6        # 42.5) MHz, the active bandwidth of the RSA
    #snr-threshold-power: 6.0
    sigma-threshold: 4.0
    normalize: true
    neighborhood-radius: 2


seq-tr-clust:
    min-frequency: 5e6
    max-frequency: 95e6
    initial-slope : 800e6                # slope of a track with 1 point
    slope-method: weighted-first-point-ref
    n-slope-points: 10
    time-gap-tolerance: 0.1e-3
    frequency-acceptance: 56e3
    trimming-threshold: 6            # snr threshold for the first and last point of a candidate
    min-points: 3
    min-slope: 0

otc:
    max-track-width: 150e3          # For most tracks this only needs to be 150e3-ish. Only curved tracks profit from this number being bigger

itc:
    time-gap-tolerance: 1.0e-3
    frequency-acceptance: 100.0e3
    max-track-width: 100.0e3

tr-proc-ws:
    min-slope: 0

mptb:
    sideband-time-tol: 1e-3

mpeb:
    jump-time-tol: 3.0e-3

ac1b:
    seq-line-nup-cut:
        min-total-nup: 0
        min-average-nup: 7.0
        time-or-bin-average: bin
        wide-or-narrow: wide

event-nup-cut:
    ntracks-npoints-nup-cut:      # cut events if the summed or average nup is below threshold
        wide-or-narrow: wide        # wide is default
        time-or-bin-average: bin

        default-parameters: # default-parameters are thresholds for event first track nup cut
            min-total-nup: 0
            min-average-nup: 7.454357052489394
            min-max-nup: 0

        parameters:
          - ft-npoints: 3
            ntracks: 1
            min-total-nup: 0
            min-average-nup: 15.74668644848628
            min-max-nup: 0

          - ft-npoints: 3
            ntracks: 2
            min-total-nup: 0
            min-average-nup: 14.396403491431705
            min-max-nup: 0

          - ft-npoints: 3
            ntracks: 3
            min-total-nup: 0
            min-average-nup: 13.032932650345844
            min-max-nup: 0

          - ft-npoints: 3
            ntracks: 4
            min-total-nup: 0
            min-average-nup: 11.651179906121854
            min-max-nup: 0

          - ft-npoints: 3
            ntracks: 5
            min-total-nup: 0
            min-average-nup: 10.242207772240628
            min-max-nup: 0

          - ft-npoints: 3
            ntracks: 6
            min-total-nup: 0
            min-average-nup: 8.78782196327628
            min-max-nup: 0

          - ft-npoints: 4
            ntracks: 1
            min-total-nup: 0
            min-average-nup: 12.735418234003228
            min-max-nup: 0

          - ft-npoints: 4
            ntracks: 2
            min-total-nup: 0
            min-average-nup: 11.681651640175646
            min-max-nup: 0

          - ft-npoints: 4
            ntracks: 3
            min-total-nup: 0
            min-average-nup: 10.610759932504259
            min-max-nup: 0

          - ft-npoints: 4
            ntracks: 4
            min-total-nup: 0
            min-average-nup: 9.515056968514685
            min-max-nup: 0

          - ft-npoints: 4
            ntracks: 5
            min-total-nup: 0
            min-average-nup: 8.379691045166915
            min-max-nup: 0

          - ft-npoints: 5
            ntracks: 1
            min-total-nup: 0
            min-average-nup: 10.869025304065605
            min-max-nup: 0

          - ft-npoints: 5
            ntracks: 2
            min-total-nup: 0
            min-average-nup: 9.987041877860296
            min-max-nup: 0

          - ft-npoints: 5
            ntracks: 3
            min-total-nup: 0
            min-average-nup: 9.083012737896947
            min-max-nup: 0

          - ft-npoints: 5
            ntracks: 4
            min-total-nup: 0
            min-average-nup: 8.144983909889586
            min-max-nup: 0

          - ft-npoints: 6
            ntracks: 1
            min-total-nup: 0
            min-average-nup: 9.831510394306793
            min-max-nup: 0

          - ft-npoints: 6
            ntracks: 2
            min-total-nup: 0
            min-average-nup: 9.148730213081482
            min-max-nup: 0

          - ft-npoints: 6
            ntracks: 3
            min-total-nup: 0
            min-average-nup: 8.436488780835134
            min-max-nup: 0

          - ft-npoints: 6
            ntracks: 4
            min-total-nup: 0
            min-average-nup: 7.67794591793375
            min-max-nup: 0

          - ft-npoints: 7
            ntracks: 1
            min-total-nup: 0
            min-average-nup: 8.893879615160312
            min-max-nup: 0

          - ft-npoints: 7
            ntracks: 2
            min-total-nup: 0
            min-average-nup: 8.294285562892895
            min-max-nup: 0

          - ft-npoints: 7
            ntracks: 3
            min-total-nup: 0
            min-average-nup: 7.658861173418163
            min-max-nup: 0

          - ft-npoints: 8
            ntracks: 1
            min-total-nup: 0
            min-average-nup: 8.277213651025455
            min-max-nup: 0

          - ft-npoints: 8
            ntracks: 2
            min-total-nup: 0
            min-average-nup: 7.722303890626092
            min-max-nup: 0

          - ft-npoints: 9
            ntracks: 1
            min-total-nup: 0
            min-average-nup: 7.9962037692806796
            min-max-nup: 0

          - ft-npoints: 9
            ntracks: 2
            min-total-nup: 0
            min-average-nup: 7.46339335340889
            min-max-nup: 0

          - ft-npoints: 10
            ntracks: 1
            min-total-nup: 0
            min-average-nup: 7.725369787485035
            min-max-nup: 0

          - ft-npoints: 11
            ntracks: 1
            min-total-nup: 0
            min-average-nup: 7.454357052489394
            min-max-nup: 0

event-time-cut:
    event-time-in-acq-cut:
        min-time: 0.5e-3
        max-time: 5


egg3:
    filename: "foo.egg"
    egg-reader: egg3
    number-of-slices: 0
    slice-size: 4096
    progress-report-interval: 10000

fft3:
    transform-flag: ESTIMATE



spectrogram1:
    min-frequency: 0e6
    max-frequency: 100e6
    lead-time: 40e-5
    trail-time: 40e-5
    lead-freq: 100e3
    trail-freq: 100e3
    use-track-freqs: true
    full-event: true

brw:
    output-file: "KTOutput/GainVariation.root"
    file-flag: recreate

trw:
    output-file: "KTOutput/SparseSpectrogram.root"
    file-flag: recreate

writer:
    output-file: "KTOutput/RawSpectrogram.root"
    file-flag: recreate
    #min-time: 0.0
    #max-time: 1
    min-freq: 0
    max-freq: 100.0e6
